name: calatube
description: Calatube - YouTube Music, sans pub
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.9.0
  webview_flutter_android: ^3.16.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/noutube_inject.js

  fonts:
    - family: SuperWonder
      fonts:
        - asset: assets/fonts/SuperWonder.ttf
